# Generated by Django 2.2.3 on 2019-07-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseNum', models.CharField(max_length=200)),
                ('CourseName', models.CharField(max_length=200)),
                ('Credits', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
            ],
        ),
    ]
