# Generated by Django 2.2.3 on 2019-07-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Topics',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
