# Generated by Django 2.2.3 on 2019-07-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobrelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=200)),
                ('JobTitle', models.CharField(max_length=200)),
                ('CityState', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=500)),
                ('JobUrl', models.CharField(max_length=1000)),
                ('ResearchArea', models.CharField(max_length=200)),
                ('ResearchKeyWord', models.CharField(max_length=500)),
            ],
        ),
    ]
