# Generated by Django 2.2.3 on 2019-07-28 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrelated',
            old_name='ResearchArea',
            new_name='AreaName',
        ),
    ]
