# Generated by Django 2.2.3 on 2019-07-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseNum', models.CharField(max_length=200)),
                ('AreaName', models.CharField(max_length=500)),
            ],
        ),
    ]
